import type { SmartResult } from './smartScan'
import type { ChkdskResult } from './chkdskScan'

// ── Types ────────────────────────────────────────────────────────────────────

export type HealthStatus = 'PASSED' | 'WARNING' | 'FAILED' | 'UNKNOWN'

export interface HealthScore {
  score: number
  status: HealthStatus
  issues: string[]
  summary: string
  // keeping deductions for backward compatibility, although not explicitly requested
  deductions: { reason: string; points: number }[]
}

// ── Scoring rules ─────────────────────────────────────────────────────────────

export interface ScorePayload {
  smart: SmartResult | null
  chkdsk: ChkdskResult | null
  temperature: number | null  // °C, can override SMART temp
}

export function calculateHealthScore(payload: ScorePayload): HealthScore {
  const { smart, chkdsk, temperature } = payload
  let score = 100
  const deductions: { reason: string; points: number }[] = []
  const issues: string[] = []

  let isFailed = false
  let isWarning = false
  let isUnknown = false

  const deduct = (points: number, reason: string) => {
    score -= points
    deductions.push({ reason, points })
  }

  // Use effective temperature
  const temp = temperature ?? smart?.temperature ?? null

  if (!smart || smart.fallback || !smart.available) {
    isUnknown = true
  } else {
    // Incorporate issues generated by smartScan.ts
    if (smart.issues && smart.issues.length > 0) {
      issues.push(...smart.issues)
      
      for (const issue of smart.issues) {
        if (issue.toLowerCase().includes('bad sectors')) {
          deduct(20, 'Reallocated sectors')
          isWarning = true
        }
        if (issue.toLowerCase().includes('pending sectors')) {
          deduct(30, 'Pending sectors')
          isFailed = true
        }
        if (issue.toLowerCase().includes('high temperature')) {
          deduct(15, 'High temperature')
          isWarning = true
        }
        if (issue.toLowerCase().includes('aging')) {
          deduct(25, 'Low SSD wear level')
          isWarning = true
        }
        if (issue.toLowerCase().includes('failure')) {
          deduct(50, 'Drive reported failure')
          isFailed = true
        }
      }
    }
    
    // Check bad sectors from chkdsk
    if (chkdsk && chkdsk.badSectors > 0) {
      issues.push(`${chkdsk.badSectors} KB of bad sectors found by chkdsk`)
      isWarning = true
    }
  }

  // Clamp to [0, 100]
  score = Math.max(0, Math.min(100, score))

  // ── Derive status & summary ────────────────────────────────────────────────────────
  let status: HealthStatus
  let summary = ''

  if (isUnknown) {
    status = 'UNKNOWN'
    summary = 'SMART data not available. Run as Administrator.'
  } else if (isFailed) {
    status = 'FAILED'
    summary = 'Drive is at high risk of failure. Backup immediately.'
  } else if (isWarning) {
    status = 'WARNING'
    summary = 'Drive is degrading. Issues detected.'
  } else {
    status = 'PASSED'
    summary = 'Drive is healthy and working normally'
  }

  return { score, status, issues, summary, deductions }
}
